name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build Number Generator
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}

    - name: Build image
      run: make docker-build docker-push IMG="dobolinux/:v0.0.${{ steps.buildnumber.outputs.build_number }}"
