name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Number Generator
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}

    - name: Build image
      run: make docker-build docker-push IMG="dobolinux/:v0.0.${{ steps.buildnumber.outputs.build_number }}"
